name: darting
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: desenvolv4 <gabriel>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  intl: ^0.15.8

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
